version: '3.7'

services:
  api:
    build: .
    container_name: api
    restart: always
    working_dir: /app
    command: ./api
    ports:
      - 8081:8080
    env_file: api.env
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.2-bionic
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    env_file: api.env

volumes:
  mongodata:
