version: '3.8'

services:
  api:
    build: .
    container_name: api
    restart: unless-stopped
    ports:
      - 8081:8080
    env_file: api.env
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.2-bionic
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./volmes/mongo:/data/db
    env_file: api.env
