name: docker base image update

on:
  schedule:
    - cron: '0 1 * * *'
    
env:
  BASE_IMAGE: library/alpine
  BASE_IMAGE_TAG: latest
  IMAGE_NAME: pruh/api
  IMAGE_TAG: alpine

jobs:

  push:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1.1.1
        with:
          base-image: ${{ env.BASE_IMAGE }}:${{ env.BASE_IMAGE_TAG }}
          image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      # only execute subsequent steps if an update is actually NEEDED.
      # unfortunately we need to add an if-condition to all steps now
      # because a clean exit can't be triggered within a job it seems
      # (a cancellation is NOT the same and triggers a failure email)
      # see also https://github.com/actions/runner/issues/662

      - name: Get latest release version
        id: release_version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: pruh/api
          excludes: prerelease, draft
        if: steps.check.outputs.needs-updating == 'true'

      - name: normalize version
        id: version
        run: |
          echo release_version=$(echo ${{ steps.release_version.outputs.release }} |
            sed 's/release-//') >> $GITHUB_OUTPUT
        if: steps.check.outputs.needs-updating == 'true'

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: steps.check.outputs.needs-updating == 'true'

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: "${{ github.workspace }}"
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.release_version }}-${{ env.IMAGE_TAG }}
        if: steps.check.outputs.needs-updating == 'true'
