name: docker base image update

on:
  release:
    types: [published]
    
env:
  BASE_IMAGE: library/alpine
  BASE_IMAGE_TAG: latest
  IMAGE_NAME: pruh/api
  IMAGE_TAG: alpine

jobs:

  push:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Get base image latest version
        id: version
        run: | 
              echo alpine_version=$(curl -L --fail "https://hub.docker.com/v2/repositories/${{ env.BASE_IMAGE }}/tags/?page_size=100" | 
                jq '.results | .[] | .name' -r |
                grep -Po "(\d+\.)+\d+" |
                sort --version-sort |
                tail -n 1) >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: "${{ github.workspace }}"
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.alpine_version }}-${{ env.IMAGE_TAG }}
