name: docker push on release

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]
  # release:
  #   types: [published]
    
env:
  BASE_IMAGE: library/alpine
  BASE_IMAGE_TAG: latest
  IMAGE_NAME: pruh/api
  IMAGE_TAG: alpine

jobs:

  push:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Get latest release version
        id: version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: pruh/api
          excludes: prerelease, draft

      - name: debug
        run: |
          echo ${{ steps.version.outputs.release }}

      # - name: Login to DockerHub
      #   uses: docker/login-action@v2.1.0
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push Docker images
      #   uses: docker/build-push-action@v3.2.0
      #   with:
      #     context: "${{ github.workspace }}"
      #     push: true
      #     tags: |
      #       ${{ env.IMAGE_NAME }}:latest
      #       ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      #       ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.alpine_version }}-${{ env.IMAGE_TAG }}
